services:
    qsr:
        build:
            context: ./
            dockerfile: .docker/Dockerfile
        image: qsr:build
        container_name: qsr
        hostname: qsr.localhost
        env_file:
            - .env
        ports:
            - ${APP_PORT:-80}:80
            - ${SSL_PORT:-443}:443
            - ${VITE_PORT:-5173}:5173
        networks:
            - net-sso
        extra_hosts:
            - "host.docker.internal:host-gateway"
        platform: linux/amd64
        volumes:
            - ./:/app
            - /app/vendor         # proteger dependencias PHP
            - /app/node_modules   # proteger dependencias JS            -
networks:
    net-sso:
        driver: bridge
